table 'Band Rate'
	lineageTag: dd7180cb-da84-40b8-9c1f-3d139c3ab5d9

	column Country
		dataType: string
		lineageTag: 52cc71c1-6bb2-4093-8fa5-3874e8e3a06a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Band
		dataType: string
		lineageTag: 5fcbc82e-e9f4-43b2-b4d9-cef66aa1d384
		summarizeBy: none
		sourceColumn: Band

		annotation SummarizationSetBy = Automatic

	column 'Band Code'
		dataType: string
		lineageTag: 4d49a3ad-412a-44cf-ac55-5584ca66650f
		summarizeBy: none
		sourceColumn: Band Code

		annotation SummarizationSetBy = Automatic

	column 'Effective from'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f9a0383e-9de0-4fff-a6fb-206b87620aa4
		summarizeBy: none
		sourceColumn: Effective from

		variation Variation
			isDefault
			relationship: 5b30be08-7983-4bf8-8f19-ff1fb8d1d190
			defaultHierarchy: LocalDateTable_a288e66f-9b26-4953-8933-b4285027d70f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Band Number'
		dataType: string
		lineageTag: ffa2c1d4-f0f8-4ddf-abaf-fd5f5afcb8bf
		summarizeBy: none
		sourceColumn: Band Number

		annotation SummarizationSetBy = Automatic

	column KEY
		dataType: string
		lineageTag: 6e062dae-d2d4-4c5c-af28-36153b573aea
		summarizeBy: none
		sourceColumn: KEY

		annotation SummarizationSetBy = Automatic

	column 'Threshold Category' =
			
			SWITCH(
			    TRUE(),
			     <= 0.80, "80% or below",
			    [Monthly Utilization] <= 1.20, "80-120%",
			    "120% and above"
			)
		lineageTag: edaaf7e7-0fbc-4eee-b3dc-c98e9a078a71
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Column
		type: calculated
		lineageTag: 6083e3b9-f148-4c05-a48f-dbaa5b4065c3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	column 'Bill Rate'
		dataType: double
		lineageTag: c9c7a399-d3c2-41da-a066-d681129a4cb8
		summarizeBy: sum
		sourceColumn: Bill Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Band Rate' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Sakshi\OneDrive - ProcDNA Analytics Pvt. Ltd\00_Internal Projects - Dataset\Band Rate.xlsx"), null, true),
				    #"Band Rate_Sheet" = Source{[Item="Band Rate",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Band Rate_Sheet", [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{" Bill Rate ", "Bill Rate"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Country", type text}, {"Band", type text}, {"Band Code", type text}, {"Effective from", type date}, {"Band Number", type text}, {"Bill Rate", type number}, {"KEY", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

